spring:
  application:
    name: store-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.11.13:5432/misaka
    username: misaka
    password: mikoto
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath*:/mapping/*.xml
  type-aliases-package: com.volkruss.demo.entity